[package]
name = "odeir"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cxx-build = "1.0.94"

[dependencies]
cxx = "1.0.94"
minijinja = "0.30.6"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.88"
