name: Rustfmt

on:
  pull_request:
    branches:
      - '**'

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Use Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      
      - name: Run Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
